"""booking-table-update

Revision ID: 16087e04a860
Revises: a75bd50a5e54
Create Date: 2026-03-21 01:45:39.942147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16087e04a860'
down_revision = 'a75bd50a5e54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_type', sa.Enum('private_rent', 'game_join', name='booking_type_types'), nullable=False))
        batch_op.add_column(sa.Column('participant_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('booking_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('payment_status', sa.Enum('unpaid', 'paid', name='payment_status_types'), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('client_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('turf_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('turf_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('client_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('booking_date')
        batch_op.drop_column('participant_count')
        batch_op.drop_column('booking_type')

    # ### end Alembic commands ###
