"""booking-table-migrations-update

Revision ID: 3214813519c0
Revises: 664f4edd65a7
Create Date: 2026-03-22 12:26:22.523385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3214813519c0'
down_revision = '664f4edd65a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('participant_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('turfs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('price_per_hour',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turfs', schema=None) as batch_op:
        batch_op.alter_column('price_per_hour',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('participant_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
