"""game table migration update

Revision ID: 664f4edd65a7
Revises: 16087e04a860
Create Date: 2026-03-21 19:39:08.393140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664f4edd65a7'
down_revision = '16087e04a860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_players', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price_per_player', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('price_per_player')
        batch_op.drop_column('max_players')

    # ### end Alembic commands ###
