"""initial migration

Revision ID: a75bd50a5e54
Revises: 
Create Date: 2026-02-25 09:31:30.176916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a75bd50a5e54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'owner', 'manager', 'staff', name='admin_role_types'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('email', name=op.f('uq_admins_email'))
    )
    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('skill_level', sa.Enum('beginner', 'intermediate', 'advanced', name='skill_level_types'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients')),
    sa.UniqueConstraint('email', name=op.f('uq_clients_email'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_notifications_client_id_clients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_teams_client_id_clients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_table('tournaments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('upcoming', 'ongoing', 'completed', 'cancelled', name='tournament_status_types'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk_tournaments_admin_id_admins')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournaments'))
    )
    op.create_table('turfs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_per_hour', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk_turfs_admin_id_admins')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turfs'))
    )
    op.create_table('games',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('turf_id', sa.String(length=36), nullable=True),
    sa.Column('tournament_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('game_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('open', 'full', 'cancelled', 'completed', name='game_status_types'), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_games_tournament_id_tournaments')),
    sa.ForeignKeyConstraint(['turf_id'], ['turfs.id'], name=op.f('fk_games_turf_id_turfs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.create_table('tournament_teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_tournament_teams_team_id_teams')),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_tournament_teams_tournament_id_tournaments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournament_teams')),
    sa.UniqueConstraint('tournament_id', 'team_id', name='uq_tournament_team')
    )
    op.create_table('bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('turf_id', sa.String(length=36), nullable=True),
    sa.Column('game_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', name='booking_status_types'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_bookings_client_id_clients')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_bookings_game_id_games')),
    sa.ForeignKeyConstraint(['turf_id'], ['turfs.id'], name=op.f('fk_bookings_turf_id_turfs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_reviews_booking_id_bookings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('booking_id', name=op.f('uq_reviews_booking_id'))
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'refunded', name='transaction_status_types'), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_transactions_booking_id_bookings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('reviews')
    op.drop_table('bookings')
    op.drop_table('tournament_teams')
    op.drop_table('games')
    op.drop_table('turfs')
    op.drop_table('tournaments')
    op.drop_table('teams')
    op.drop_table('notifications')
    op.drop_table('clients')
    op.drop_table('admins')
    # ### end Alembic commands ###
